apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "comments-system.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace }}
  annotations:
    description: "Namespace para el sistema de comentarios"