{{- if .Values.networkPolicies.enabled }}
{{- if .Values.networkPolicies.denyAll }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "comments-system.fullname" . }}-deny-all
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "comments-system.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
{{- end }}