{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "comments-system.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "comments-system.frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "comments-system.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Permitir tr√°fico desde el Router de OpenShift
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
    ports:
    - protocol: TCP
      port: {{ .Values.ports.frontend }}
  egress:
  # Permitir llamadas al backend-api
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "comments-system.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: backend-api
    ports:
    - protocol: TCP
      port: {{ .Values.ports.backendApi }}
  # Permitir DNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
    ports:
    - protocol: UDP
      port: 53
{{- end }}