apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comments-system.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "comments-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Credenciales de PostgreSQL
  DB_PASSWORD: "{{ .Values.postgresql.password }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.password }}"
  POSTGRES_USER: "{{ .Values.postgresql.username }}"
  POSTGRES_DB: "{{ .Values.postgresql.database }}"