apiVersion: v1
kind: Service
metadata:
  name: {{ include "comments-system.fullname" . }}-backend-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "comments-system.backend-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ports.backendApi }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "comments-system.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend-api