apiVersion: v1
kind: Service
metadata:
  name: {{ include "comments-system.fullname" . }}-database
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "comments-system.database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgresql.port }}
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    app.kubernetes.io/name: {{ include "comments-system.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database